### ISSUE TITLE
build instructions?

### ISSUE THREAD

**Issue by rotten** [michelp/pggraphblas#2]
I'd like to try to get this to build, and then add the extension to my test database rather than spinning up a docker image.

Can you provide some tips on how to get it built?  Is there a particular graphblas library that should be used (there appear to be several out there)?  Is there a particular version of postgresql this has to work on, or will it work with 11.2?

**Comment by michelp** [comment]
pggraphblas requires SuiteSparse:GraphBLAS 2.3.2 (the latest reference implementation) as it uses several extensions to the API.  It also requires the master branch of the LAGraph algorithm collection.  

http://faculty.cse.tamu.edu/davis/GraphBLAS.html
https://github.com/GraphBLAS/LAGraph

It uses the standard postgres extension building mechanism, so if you have postgres installed (only tested so far with 11.2) all you have to do is 'make && make install' to compile and install into your postgres.  The make install will likely need to be done sudo on a typical system.

While not needing docker, the Dockerfile is actually pretty good documentation for the build process, it shows how to download, compile, and install, all the dependencies.  Just do everything that starts with RUN on the command line.

I'll try and work up some build instructions in the README, and if you happen to come up with your own, feel free to send a PR!
